number = int(input("Enter Number : "))
print(number,"x",1,"=",number*1)
print(number,"x",2,"=",number*2)
print(number,"x",3,"=",number*3)
print(number,"x",4,"=",number*4)
print(number,"x",5,"=",number*5)